#!/usr/bin/env bash
#
# Restore a Supabase pg_dump into the local compose Postgres.
#
# Usage:
#   bash scripts/db/restore-dump.sh [path/to/dump]
#
# With no argument, picks the newest file in db/dump/.
#
# Re-runnable: drops and recreates the public schema first, so you can iterate
# without `docker compose down -v`.
#
# A full-project Supabase dump references roles (anon, authenticated,
# service_role, supabase_admin) and the auth/storage/extensions schemas that do
# not exist here. Those errors are expected and benign. ON_ERROR_STOP is left off
# for .sql dumps for that reason -- but READ THE ERRORS. A failed CREATE TABLE
# hidden among 200 role errors is how you end up with a half-restored database.
#
# Prefer dumping with:
#   pg_dump -Fc --no-owner --no-privileges --schema=public
set -euo pipefail

cd "$(dirname "$0")/../.."

DUMP="${1:-}"
if [[ -z "$DUMP" ]]; then
  DUMP="$(ls -t db/dump/*.dump db/dump/*.sql db/dump/*.backup 2>/dev/null | head -1 || true)"
fi

if [[ -z "$DUMP" || ! -f "$DUMP" ]]; then
  echo "error: no dump found. Put one in db/dump/ or pass a path." >&2
  echo "       looked for db/dump/*.{dump,sql,backup}" >&2
  exit 1
fi

echo "==> Using dump: $DUMP"

docker compose up -d --wait postgres

echo "==> Dropping and recreating schema public"
docker compose exec -T postgres psql -U capri -d capri -q \
  -c 'DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public;'

echo "==> Restoring"
case "$DUMP" in
  *.dump|*.backup)
    # pg_restore exits non-zero on ignorable errors; capture and report instead.
    if ! docker compose exec -T postgres pg_restore -U capri -d capri \
           --no-owner --no-privileges --schema=public < "$DUMP"; then
      echo "note: pg_restore reported errors (usually Supabase roles/schemas). Review above." >&2
    fi
    ;;
  *.sql)
    docker compose exec -T postgres psql -U capri -d capri -v ON_ERROR_STOP=0 < "$DUMP"
    ;;
  *)
    echo "error: unrecognised dump extension: $DUMP" >&2
    exit 1
    ;;
esac

echo "==> Tables restored:"
docker compose exec -T postgres psql -U capri -d capri -c '\dt'

cat <<'EOF'

==> Next steps
  1. Inspect the schema before writing any code:
       bash scripts/db/inspect.sh
     Specifically confirm appointment.id is serial / GENERATED BY DEFAULT
     (not GENERATED ALWAYS), and check the timestamp and numeric types.
  2. Generate the Drizzle schema from what you actually got:
       pnpm db:pull
  3. Rewrite photo URLs and sync sequences:
       pnpm db:psql -f /db/sql/100_rewrite_photo_urls.sql
       pnpm db:psql -f /db/sql/110_sync_sequences.sql
EOF
