export enum WebhookEvent {
    BOOKING_CANCELED = "BOOKING_CANCELED",
    BOOKING_REJECTED = "BOOKING_REJECTED",
    BOOKING_CREATED = "BOOKING_CREATED",
    BOOKING_REQUESTED = "BOOKING_REQUESTED",
    BOOKING_RESCHEDULED = "BOOKING_RESCHEDULED"
}